### ISSUE TITLE
Softkeybord not responding

### ISSUE THREAD

**Issue by Marco82** [jackpal/Android-Terminal-Emulator#129]
I am using  a Galaxy  Tab  2 10.1 and  my  software keyboard  is not  responding at all.
The  terminal does not show and  run any of my inputs .

I can not use another terminal Software, because i do like to use octave for android .

**Comment by Stemby** [comment]
Same problem here with a Samsung Galaxy Tab 10.1N (GT-P7501): nearly all keys work, but not the alphabetic ones.

**Comment by jackpal** [comment]
Sorry, this is a long-standing problem with some models of Samsung. Another work-around is to install and use the free Hacker's IME keyboard instead of the regular Samsung IME.

https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en
