### ISSUE TITLE
Screen flashing when active brightness control app

### ISSUE THREAD

**Issue by pylerSM** [jackpal/Android-Terminal-Emulator#364]
Steps to reproduce:
1, Download Darken app (app to control brightness)
2, Run it
3, Launch Terminal emulator 

We need warning or something like this..

**Comment by jackpal** [comment]
Huh, that's strange. I don't think the terminal emulator is doing anything special with colors that would cause a problem like this.

Unfortunately I don't have time to chase down why this is happening...
