### ISSUE TITLE
cant use included software from other terminals (like a remote ssh)

### ISSUE THREAD

**Issue by kaefert** [jackpal/Android-Terminal-Emulator#370]
Hi there!

I'm trying to use the htop included in you're android app from a remote ssh session, but I only get:

```
user@android:/data/data/com.spartacusrex.spartacuside/files/system/bin # ./htop
Error opening terminal: xterm.
```
(I've tried `export TERM=linux` and a few others but the error message stays the same but for the name..)

trying to use the included bash gives me:
```
bash: precmd: command not found
```

please help

**Comment by jackpal** [comment]
I think there's some confusion, because TEA doesn't include any software like htop.

**Comment by kaefert** [comment]
whups, sorry, you're right. that was a mixup. I thought I had found a repository of this app called "Terminal IDE" -->
https://play.google.com/store/apps/details?id=com.spartacusrex.spartacuside
which includes a few apps like htop.
sorry.
