### ISSUE TITLE
Documentation for using TEA as a service/library

### ISSUE THREAD

**Issue by bmillare** [jackpal/Android-Terminal-Emulator#380]
Background:
I'm trying to develop an application for the Samsung Gear VR which goal is to create a virtual office space with applications displayed in 3D space instead of just directly on the phone display. For more motivation, imagine you are on a budget commercial airline, distracted by crying babies and claustrophobic seating conditions, however, you still want to keep developing on your next big application. Instead of pulling out a small laptop with its small screen, you attach your phone to your mobile VR headset, pullout your bluetooth keyboard, and start programming with multiple virtual monitors at a beautiful beach and sun.

Currently as is, I need to be able to override a view's onDraw method to use a special canvas that draws to a openGL texture instead of the usual. This way, I can use that texture to display the app in 3D space and for both eyes, instead of directly to the screen. To make this work with terminal emulator, my understanding is to override EmulatorView's onDraw. 

Problem:
The problem now is, I will include EmulatorView in my application but I need to pass it a session which would normally be on the service process (or thread?). How to link EmulatorView on my process to the service process, perhaps using RemoteInterface, is not well described.

Request:
Can there be documentation on how to use TEA as a service or library, whether it needs to be included within my own application (or which subset), and then psuedo code to connect an EmulatorView to a TerminalService (is that even the correct approach?)?

Suggested Contact:
@steven676

**Comment by steven676** [comment]
The sample application for the library used to be a part of TEA source, but disappeared with the Android Studio/gradle conversion; you can get it out of the Git history (https://github.com/jackpal/Android-Terminal-Emulator/tree/v1.0.62/examples/widget).  There's also API documentation which you can get by running Javadoc on the library source; if you're lazy, there used to be a copy in the source tree (https://github.com/jackpal/Android-Terminal-Emulator/tree/v1.0.62/libraries/emulatorview/docs), but I believe that copy was out of date anyway.

**Comment by bmillare** [comment]
Thanks, closing.

**Comment by jackpal** [comment]
I'll see if I can bring back the examples and make them build under the new gradle build system.

**Comment by bmillare** [comment]
That would be much appreciated! Thanks

**Comment by steven676** [comment]
Would be helpful for Gradle conversion to convert the widget sample to use JNI instead of a helper binary?  That would eliminate the need for the oddball build system (and probably make the sample match what most people actually want to do).  We'd lose (legacy) Google TV compatibility, but (1) I'm guessing no one used that and (2) anyone who cares can dig the old code out of the 1.0.62 source.

**Comment by jackpal** [comment]
I have added the samples to the gradle build.

The intents sample seems to work ok.

I renamed the widget sample to "telnet" and cut out the Google TV related
code. I broke the local shell code when I did that. Steven, could you help
me fix that

As for the third sample, path broadcasts, it builds but doesn't show up as
a launcher icon. I'm not sure what is wrong with it.
