### ISSUE TITLE
Term shortcut widget not working

### ISSUE THREAD

**Issue by bdantas** [jackpal/Android-Terminal-Emulator#384]
I created a home screen widget like this:
  Command: /system/bin/sh
  Arguments: /storage/emulated/0/Download/myscript.sh

When I click on the newly-created icon, a terminal opens and some random characters (3;60R) appear on the command line, but my script does not run. Opening a terminal and typing the command and argument cause the script to run as expected.

Am I not using the widget correctly, or is it broken?

---------------
Terminal Emulator: 1.0.65
OS: CM11
Device: Moto G

**Comment by FrankWestlake** [comment]
>Command: /system/bin/sh
>Arguments: /storage/emulated/0/Download/myscript.sh
>
>When I click on the newly-created icon, a terminal opens and some random characters (3;60R)
> appear ...

If your script runs 'resize' then comment that out and try again. 

Frank

**Comment by bdantas** [comment]
My script does not contain the resize command. As a test, I created an uber-simple script with nothing but simple commands (ls, echo, read) and still can't get a working shortcut.

**Comment by bdantas** [comment]
On my Replicant tablet with same version of TEA, this shortcut setup worked fine (command intentionally left blank):

 Command:
 Arguments: sh /storage/emulated/0/Download/test.sh

However, the above on my Moto G still just opens a terminal with a command prompt that looks like this:
u0_a55@falcon_cmda:/ $ 9;60R

This is driving me nuts and I don't know what else to try. I have many nice scripts that I would love to be able to launch from my Moto G's homescreen :(

---------------------
Terminal Emulator: 1.0.65
 OS: CM11
 Device: Moto G

**Comment by FrankWestlake** [comment]
Compare the two 'busybox' versions with the latest available; maybe the Moto G needs to be updated.

**Comment by bdantas** [comment]
Thanks for the tip. Here are the Busybox versions:
Moto G (main device, causing problems): 1.22.1
GalaxyTab (don't use much, with Replicant): 1.21.1
Current stable busybox version according to their website: 1.23.1

Since both the Moto G and GalaxyTab have TEA 1.0.65 and the GalaxyTab busybox is *older* that the one in the Moto G, I don't think the fact that the outdated Moto G busybox is the problem.

**Comment by FrankWestlake** [comment]
It is common for one release to add an error that the next release is intended to fix. 

Frank

**Comment by bdantas** [comment]
I downgraded busybox on my Moto G to 1.21.1 but that didn't help.

Just to be thorough, I decided to take a close look at /system/etc/mksh. Lo and behold, there was a resize comment in there. I commented it out and now the Term shortcuts work beautifully. If it wasn't for your initial advice, there is absolutely no way I could have solved this. THANK YOU, FRANK!!!!!

**Comment by FrankWestlake** [comment]
From bdantas:
>...I decided to take a close look at /system/etc/mksh.
>Lo and behold, there was a resize comment in there. I  
commented it out and
>now the Term shortcuts work beautifully.

Thanks for letting us know where the problem is!

Frank
