### ISSUE TITLE
How to make a persistent command history?

### ISSUE THREAD

**Issue by bdantas** [jackpal/Android-Terminal-Emulator#385]
My command history starts from scratch each time I use the terminal emulator app. Is there a way to make the history persistent?

----------------
Terminal Emulator: v1.0.65
 OS: CM11
 Device: Moto G

**Comment by jackpal** [comment]
Sorry, that's a general Linux-on-Android question, and I don't have the knowledge or time to help you with that. Maybe ask on the xda-developers forum?
