### ISSUE TITLE
Quit the app from command line?

### ISSUE THREAD

**Issue by bdantas** [jackpal/Android-Terminal-Emulator#386]
Is there a command that will close all terminal windows and the Terminal Emulator app, so that I am back to my device's homescreen? I'd like to add such a command to the end of one of my scripts (after the final "exit 0").

I've tried all the logical possibilities (quit, close, done, shutdown, end) and no luck.

----------------
Terminal Emulator: v1.0.65
 OS: CM11
 Device: Moto G

**Comment by FrankWestlake** [comment]
>Is there a command that will close all terminal windows and the Terminal Emulator app,...

No, but if you are running a script from a shortcut and want TEA to close after the script completes then include 'exit' in the arguments window of the shortcut dialog: 

  Arguments: [ myScript; exit]

Frank

**Comment by bdantas** [comment]
Great tip, Frank. Thanks. Now if only I can get the shortcut dialogs to work...
