### ISSUE TITLE
Please source a user-writable .mkshrc in  /system/etc/mkshrc

### ISSUE THREAD

**Issue by bdantas** [jackpal/Android-Terminal-Emulator#387]
I would like to request that /system/etc/mkshrc ship with a line like this (or similar):
source $HOME/.mkshrc

That way, the user has a writeable file in which to save shell preferences such as aliases, environment variables, and PATH changes. Otherwise, it becomes necessary to remount /system in rw mode (i.e., cracking a nut with a sledgehammer): https://github.com/jackpal/Android-Terminal-Emulator/issues/216

**Comment by jackpal** [comment]
Sorry, in general Android Terminal Emulator is only a terminal emulator, it can't do anything to modify the way Android works. Maybe ask CynaogenMOD or AOSP.
