### ISSUE TITLE
Material Design Refresh

### ISSUE THREAD

**Issue by jackpal** [jackpal/Android-Terminal-Emulator#388]
People would like it if the app switched from the Holo theme to a Material Design theme.

**Comment by jackpal** [comment]
I created a MaterialDesign branch to do the MaterialDesign work, and checked in a few changes.

My goal for the first release is minimal consistent Material Design theming that doesn't break back-compat with older versions of Android.

It looks like I have to set the targetSDK to 21 in order to have access to the Material Design styles.

Setting the target to 21 (previously 11) changes the behavior of some of the Android APIs, leading to some crashes. I fixed one of them, but the "Windows" list is now crashing when you tap on the "New Windows" button.

TODO:

 Check if things run on pre-Material Design versions of Android.
 Fix target 21-based crashes in the app.
 Use Material Design consistently (on widgets and dialog boxes.)
 Choose a color theme. On the one hand I'm leaning towards Android Green, on the other hand I'm leaning towards dark grey.

**Comment by jackpal** [comment]
Yaroslav Shevchuk points out that I should check earlier versions of the app to see if the crashes I'm finding are new to the Material Design version, or if they were already present in earlier versions of the app.

**Comment by FrankWestlake** [comment]
Samsung Note 3 provides some crash information that is often more useful than logcat. I can't build TEA anymore but if you could put an apk in the branch I can see if my Note 3 will report what caused the crash. 

Frank

**Comment by jackpal** [comment]
Thanks for the offer Frank! I figured out the crash, so no need to debug. (It was a mistake in some old code that happened to work on older platforms, but failed on 5.0 on a Nexus 9. Nothing to do with Material Design, it just showed up because I was testing.)

**Comment by jackpal** [comment]
As part of this I'm planning on bumping the minimum target to v7, and will start using the appcompat libraries. Probably going to switch from activities to fragments.

I'll keep an old version published for v3-v6 users. The Play store says there are about 9000 active installs of TEA on versions less that v7. (v7 == 2.1 == Eclair MR1) I wonder how many of them are actually running TEA vs. just have it installed on their phone. They're probably not happy with the size increase of the APK to support MIPS, x86, large icons, etc. Sorry folks! Might be worth making a special APK release just for them that has the other stuff stripped out of it. I wonder how bug fixes will work with split versions -- I guess the two sets of version numbers can grow in parallel.

FWIW Play Market says that 5% of people with TEA installed are running 2.3.7. That's interesting because the Play Market itself sees about 9% of users are running 2.3.7. I think this means that people who are interested in terminal emulators are also likely to be interested in higher-spec phones.

**Comment by jackpal** [comment]
Experiments show that adding the Material Design v7 app-compat library balloons the APK from 0.5 MB to 1.5 MB. That's too much! So I guess for now we'll stick with Material Design just for Android 5.0 and later.

**Comment by jackpal** [comment]
v1.0.68 has minimal material design support for Android 5.0+ devices.
