### ISSUE TITLE
amixer

### ISSUE THREAD

**Issue by syui** [jackpal/Android-Terminal-Emulator#394]
```
$ amixer sset "Speaker Function" On
```

android is a Reboot.

###Other

Nexut7 2013 wi-fi flo
app:Android Terminal Emulator (New 2015/03/12 Play Store)
chroot:Linux
command:amixer, alsa
android ver:5.0.2

~~~
$ amixer scontrols
~~~

**Comment by jackpal** [comment]
The TEA project has nothing to do with amixer, so I don't think this bug is related to TEA.
