### ISSUE TITLE
Term shortcut to run script in background (without opening a terminal)?

### ISSUE THREAD

**Issue by bdantas** [jackpal/Android-Terminal-Emulator#397]
I wrote a script that does things in the background and requires no user interaction. Is it possible to create a shortcut to run the script without opening a terminal (or in an invisible terminal)?

**Comment by jackpal** [comment]
If you don't want a terminal screen, you can use the built-in Android classes to run your script, without any need to install Terminal Emulator for Android:

http://stackoverflow.com/questions/25199307/unable-using-runtime-exec-to-execute-shell-command-echo-in-android-java-code
