### ISSUE TITLE
"Could not find com.android.support:support-annotations:21.0.0."

### ISSUE THREAD

**Issue by SacredCrumb** [jackpal/Android-Terminal-Emulator#400]
I have everything set up correctly -- SDK, NDK, local.properties, all that -- but I think the file gradle is needing is missing suddenly? I just get this error:

    $ ./tools/build-debug --info
    
    WARNING [Project: :libtermexec] Current NDK support is deprecated.  Alternative will be provided in the future.

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring project ':libtermexec'.
    > Could not resolve all dependencies for configuration ':libtermexec:_debugCompile'.
       > Could not find com.android.support:support-annotations:21.0.0.
         Searched in the following locations:
             https://jcenter.bintray.com/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.pom
             https://jcenter.bintray.com/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.jar
         Required by:
             Android-Terminal-Emulator:libtermexec:unspecified
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED

**Comment by jackpal** [comment]
I'm not a gradle expert, and I havent' seen that error before. It sounds like you need to install SDK version 21.

**Comment by SacredCrumb** [comment]
I'm thinking the file isn't being hosted anymore. I have the necessary components; NDK r10d, SDK Tools r24.1.2 -- *would I specifically need SDK Tools r21?* --, API 11, and I'm assuming SDK Build-tools 21 is important as well? I've set up everything that needed to be set up:

    pointed a local.properties file to the NDK and SDK directories in the TEA root dir
    ran ./tools/install-sdk-packages
    environment variables JAVA_HOME and ANDROID_SDK_ROOT are set

It just can't seem to find the files specified on the server. That being said, I'm still not ruling out it is something on my end since no one else is raising the same issue right now.

This might be a *highly* stupid question, but is there some component of Android Studio that is needed? That is, other than the usual SDK stuff?

**Comment by SacredCrumb** [comment]
Disregard that. I was working under the assumption that Android Studio was only needed for a graphical experience rather than CLI, but apparently it installs something else I hadn't. (I still don't know what it was exactly, as I had everything it installed *again*)

Closing!
