### ISSUE TITLE
CyanogenMod 11 Force Close "findLibrary returned null,Runtime.java,358"

### ISSUE THREAD

**Issue by MathewCNichols** [jackpal/Android-Terminal-Emulator#401]
I'm having problems on CyanogenMod 11. Galaxy S4 SCH-I545. After the install to version 1.0.66, I am getting a Java error. If I install Term.apk directly from GitHub, Terminal Emulator will work until I reboot the device, then the same error will show up in Event Log:

[7194,0,jackpal.androidterm,8961605,java.lang.UnsatisfiedLinkError,Couldn't load jackpal-termexec from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/Term.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]; findLibrary returned null,Runtime.java,358]

Any options at this point? It looks like the referenced Java library isn't being found or a dependency is missing for the CM 11 ROM.

**Comment by MathewCNichols** [comment]
CyanogenMod 11 ROM includes Term.apk as a system app. I remove the .apk and reinstalled as a standard user app. All is well once more!

**Comment by MathewCNichols** [comment]
The fix: 
• Delete Term.apk from /system/app. Reboot. 
• Install TEA from Google Play Store. 
• Copy "libjackpal-androidterm4.so" & "libjackpal-termexec.so"  from /data/data/jackpal.androidterm/lib to /system/lib. Allow new files to overwrite. Edit permissions to mirror other library files.  
• Uninstall TEA from Google Play Store. Reboot. 
• Copy Term.apk from GitHub source into /system/app. Edit permissions to mirror other system apk files.  Reboot. 
• Enjoy one of the best apps Android has to offer, reinstalled in CyanogenMod as a system apk.

**Comment by jackpal** [comment]
Please tell CyanogenMOD maintainers to copy both libjackpal-androidterm4.so and libjackpal-termexec.so to /system/lib -- I guess the problem is that we added the second library in version v1.0.66
