### ISSUE TITLE
action bar issue

### ISSUE THREAD

**Issue by pjk11** [jackpal/Android-Terminal-Emulator#409]
I can hide action bar, but if tap on top of screen, bar is not show.

**Comment by jackpal** [comment]
What version of Android are you using ? What version of Terminal Emulator
for Android are you using?

**Comment by nwaltham** [comment]
Confirm this is a problem for me too. Terminal Emulator 1.0.68, Android Version 4.4.4 ; it had been working until recently - I am a long time user of Terminal Emultator

**Comment by pjk11** [comment]
Terminal Emulator 1.0.68, Android Version 4.4.4, Xperia e3 D2203

**Comment by russell** [comment]
also can't do this :(

android 5.0.2
one plus one bacon
v1.0.68

**Comment by dvhh** [comment]
related : The application crashed when pressing the `back` button

Possible crash location
[Term.java@backKeyInterceptor](https://github.com/jackpal/Android-Terminal-Emulator/blob/master/term/src/main/java/jackpal/androidterm/Term.java#L308)
`NullpointerException`

Probably when checking for the action bar, 

Android 4.4.4 Asus TF101, 

I will also fill another bug report for the back button

**Comment by dvhh** [comment]
commit 3b10abe26728e3f4ece56ca57f701b8597585a30 removed `Theme.Holo.ActionBarOverlay` style linked to the togglable actionbar in `res/values/styles.xml ` which is still referenced in [Term.java:onCreate@356](https://github.com/dvhh/Android-Terminal-Emulator/blob/master/term/src/main/java/jackpal/androidterm/Term.java#L356) to create the view with an overlay action bar

**Comment by jackpal** [comment]
Theme.Holo.ActionBarOverlay still exists -- it is now in the values-v11/styles.xml , which is used for devices running API 11 or newer.

**Comment by dvhh** [comment]
but then there is no explanation on why `Term.onCreate` is not able to get an action bar when the style used is this one ( which is why the fix #411 is imperfect , the mActionbar is not suppose to be null when it is toggle-able ), plus the action bar is not showing on the lastest market version when in auto-hide mode, I suspect it is not created as the method in `onCreate` is suppose to get an instance of it from the layout.

**Comment by dvhh** [comment]
Should we set a [android:targetSdkVersion](http://developer.android.com/guide/topics/manifest/uses-sdk-element.html) for the actionbar to be available from the compat library
