### ISSUE TITLE
Unable to update to v1.0.69 in CM11 via F-Droid.

### ISSUE THREAD

**Issue by OpenWTF** [jackpal/Android-Terminal-Emulator#412]
F-Droid shows there is a update 1.0.69 available. F-Droid asks to first uninstall previous version because of new signing key used in 1.0.69. However, after uninstalling previous version of Terminal Emulator, a new version still cannot be installed.

Installing 1.0.69 via Google Play store is ok, without any problems.

Running CyanogenMod 11.

**Comment by jackpal** [comment]
Sorry to hear that! I guess you should report the issue to F-Droid. Not sure what to make of the signature being different. Maybe they have built their own version of the application.

I only distribute TEA through the Play store and https://jackpal.github.io/Android-Terminal-Emulator/

**Comment by OpenWTF** [comment]
OK, thanks. I'll check with F-Droid.
