### ISSUE TITLE
Support Android TV

### ISSUE THREAD

**Issue by jackpal** [jackpal/Android-Terminal-Emulator#425]
I have a Nexus Player now -- and while I can install TEA on it, the result is not usable due to overscan.

Need to:
have a TV layout that avoids the overscan area
use large text by default
TV-compatible icon

**Comment by dvhh** [comment]
Curiously the problem is identical on TF101 with the HDMI output ( minus the text size issue and icon).

Maybe the default setting for the font size could be infered from the system text size scaling ?

**Comment by dvhh** [comment]
Made an experiment with my fork, which add margins to the TermViewFlipper, but not the whole view.
I try adding some android TV detection to set the preference by default, but could not test as I do not own such device.

**Comment by dvhh** [comment]
Testing the HDMI output, the margins are ok, but yes the fontsm size are quite small. And the emulator view seems to ignore the margins, making the the overflowing on the right an bottom.

**Comment by jackpal** [comment]
dvhh -- you can test using the Android emulator. There is an "Android TV" emulator.

I don't think your approach is the right approach -- the proper thing to do is to use a different layout, with a different UI, that's designed for TV.

https://developer.android.com/training/tv/start/layouts.html
 I'm going to back out your patch because it doesn't work right.

**Comment by dvhh** [comment]
I understand, but I also wanted to solve quite the same clipping issue when outputing on hdmi, for various devices, which it solve. You can rollback if you so desire.

**Comment by jackpal** [comment]
Closing because I've decided to stop working on TEA, so this bug won't be fixed.
